image filtering node
vortexntnu/vortex-sensor-fusion pull request #23
Opened 2024-04-17 16:22 UTC by jorgenfj

2024-04-17 17:55 UTC, EirikKolas requested changes
Very nice and clean ROS code 😎. I have two suggestions.
1. Standardize the input to the filter functions. 
  - by either creating a class that stores the parameter struct as a member variable as well as all the functions
  - or making all the functions take the same parameter struct as an argument.
2. Make the `std::map` point to the function instead of an enum. The enum will become redundant in this case.

This will make it a lot easier to add new filters later: Add one function and update the map with one entry. Now you have to update the map, the enum, and the switch-case in addition to adding the function.

2024-04-17 17:55 UTC, EirikKolas commented on image_filters/params/image_filter_parameters.yaml
> +#   EBUS = 6
Forgot to remove this :)

2024-04-17 17:55 UTC, EirikKolas commented on image_filters/test/image_processing_test.cpp
bruh

2024-04-17 17:55 UTC, EirikKolas commented on image_filters/test/CMakeLists.txt
no tests :(

2024-04-18 16:42 UTC, EirikKolas approved these changes
Good job! Really liked the documentation

2024-04-18 16:42 UTC, EirikKolas commented on image_filters/README.md
Amazing! 🤩

2024-04-18 16:43 UTC, jorgenfj commented
Not finished yet. There is a CMake error when building

2024-04-18 16:44 UTC, EirikKolas commented on image_filters/params/image_filter_parameters.yaml
> +#   EBUS = 6
bump

2024-04-18 16:46 UTC, EirikKolas commented
You can access elements in the map as `filter_map["name_of_filter"]` btw. Was too small of a change to bother you to change it, but since you are already working on it... :)

2024-04-18 16:47 UTC, EirikKolas commented on image_filters/src/image_processing.cpp
> +        original.copyTo(filtered);  // Default to no filter
This can be simplified :)

2024-04-21 17:30 UTC, closed without merging